// Advanced Theme Configuration System
// Composable themes for shadcn/ui registry
// Compatible with most React/Next.js stacks

export interface ThemeConfig {
  name: string;
  title: string;
  primaryLight: string;
  primaryDark: string;
  fontSans: string;
  description: string;
  category: "minimal" | "colorful" | "branded" | "creative" | "dark";
}

export const themes: ThemeConfig[] = [
  {
    name: "default",
    title: "Default",
    primaryLight: "oklch(0.2050 0 0)",
    primaryDark: "oklch(0.9220 0 0)",
    fontSans: "ui-sans-serif, system-ui, sans-serif",
    description: "Clean neutral grayscale with system fonts",
    category: "minimal",
  },
  {
    name: "catppuccin",
    title: "Catppuccin",
    primaryLight: "oklch(0.55 0.25 297.02)",
    primaryDark: "oklch(0.79 0.12 304.77)",
    fontSans: "Montserrat, sans-serif",
    description: "Soothing pastel theme for cozy productivity",
    category: "colorful",
  },
  {
    name: "mocha-mousse",
    title: "Mocha Mousse",
    primaryLight: "oklch(0.61 0.06 44.36)",
    primaryDark: "oklch(0.73 0.05 52.33)",
    fontSans: "DM Sans, sans-serif",
    description: "Warm earthy tones inspired by coffee culture",
    category: "minimal",
  },
  {
    name: "bubblegum",
    title: "Bubblegum",
    primaryLight: "oklch(0.62 0.18 348.14)",
    primaryDark: "oklch(0.92 0.08 87.67)",
    fontSans: "Poppins, sans-serif",
    description: "Playful and vibrant pink-based theme",
    category: "colorful",
  },
  {
    name: "cosmic-night",
    title: "Cosmic Night",
    primaryLight: "oklch(0.54 0.18 288.03)",
    primaryDark: "oklch(0.72 0.16 290.40)",
    fontSans: "Inter, sans-serif",
    description: "Deep space purple with starlight accents",
    category: "dark",
  },
  {
    name: "nature",
    title: "Nature",
    primaryLight: "oklch(0.52 0.13 144.17)",
    primaryDark: "oklch(0.67 0.16 144.21)",
    fontSans: "Montserrat, sans-serif",
    description: "Fresh greens inspired by natural landscapes",
    category: "colorful",
  },
  {
    name: "cyberpunk",
    title: "Cyberpunk",
    primaryLight: "oklch(0.67 0.29 341.41)",
    primaryDark: "oklch(0.67 0.29 341.41)",
    fontSans: "Outfit, sans-serif",
    description: "Neon-powered futuristic aesthetics",
    category: "creative",
  },
  {
    name: "neo-brutalism",
    title: "Neo Brutalism",
    primaryLight: "oklch(0.65 0.24 26.97)",
    primaryDark: "oklch(0.70 0.19 23.19)",
    fontSans: "DM Sans, sans-serif",
    description: "Bold borders and high contrast design",
    category: "creative",
  },
  {
    name: "ocean-breeze",
    title: "Ocean Breeze",
    primaryLight: "oklch(0.72 0.19 149.58)",
    primaryDark: "oklch(0.77 0.15 163.22)",
    fontSans: "DM Sans, sans-serif",
    description: "Calm coastal blues and teals",
    category: "colorful",
  },
  {
    name: "sunset-horizon",
    title: "Sunset Horizon",
    primaryLight: "oklch(0.74 0.16 34.71)",
    primaryDark: "oklch(0.74 0.16 34.71)",
    fontSans: "Montserrat, sans-serif",
    description: "Warm oranges and soft evening hues",
    category: "colorful",
  },
  {
    name: "midnight-bloom",
    title: "Midnight Bloom",
    primaryLight: "oklch(0.57 0.20 283.08)",
    primaryDark: "oklch(0.57 0.20 283.08)",
    fontSans: "Montserrat, sans-serif",
    description: "Deep purples with floral undertones",
    category: "dark",
  },
  {
    name: "pastel-dreams",
    title: "Pastel Dreams",
    primaryLight: "oklch(0.71 0.16 293.54)",
    primaryDark: "oklch(0.79 0.12 295.75)",
    fontSans: "Open Sans, sans-serif",
    description: "Soft dreamy pastels for gentle interfaces",
    category: "colorful",
  },
  {
    name: "claude",
    title: "Claude",
    primaryLight: "oklch(0.62 0.14 39.04)",
    primaryDark: "oklch(0.67 0.13 38.76)",
    fontSans: "system-ui, sans-serif",
    description: "Anthropic's signature warm terracotta",
    category: "branded",
  },
  {
    name: "vercel",
    title: "Vercel",
    primaryLight: "oklch(0 0 0)",
    primaryDark: "oklch(1 0 0)",
    fontSans: "Geist, sans-serif",
    description: "Sleek black and white minimalism",
    category: "branded",
  },
  {
    name: "mono",
    title: "Mono",
    primaryLight: "oklch(0.56 0 0)",
    primaryDark: "oklch(0.56 0 0)",
    fontSans: "Geist Mono, monospace",
    description: "Pure grayscale monochrome aesthetic",
    category: "minimal",
  },
  {
    name: "modern-minimal",
    title: "Modern Minimal",
    primaryLight: "oklch(0.55 0.12 260.00)",
    primaryDark: "oklch(0.65 0.14 262.00)",
    fontSans: "Inter, sans-serif",
    description: "Ultra-clean contemporary design",
    category: "minimal",
  },
  {
    name: "t3-chat",
    title: "T3 Chat",
    primaryLight: "oklch(0.60 0.20 280.00)",
    primaryDark: "oklch(0.70 0.18 282.00)",
    fontSans: "Inter, sans-serif",
    description: "Inspired by the T3 Stack community",
    category: "branded",
  },
  {
    name: "twitter",
    title: "Twitter",
    primaryLight: "oklch(0.65 0.20 220.00)",
    primaryDark: "oklch(0.70 0.18 222.00)",
    fontSans: "system-ui, sans-serif",
    description: "Classic Twitter blue interface",
    category: "branded",
  },
  {
    name: "doom-64",
    title: "Doom 64",
    primaryLight: "oklch(0.55 0.25 25.00)",
    primaryDark: "oklch(0.60 0.22 27.00)",
    fontSans: "Oxanium, sans-serif",
    description: "Retro gaming red and dark theme",
    category: "creative",
  },
  {
    name: "graphite",
    title: "Graphite",
    primaryLight: "oklch(0.45 0.02 260.00)",
    primaryDark: "oklch(0.55 0.02 262.00)",
    fontSans: "Inter, sans-serif",
    description: "Sophisticated dark gray tones",
    category: "dark",
  },
  {
    name: "perpetuity",
    title: "Perpetuity",
    primaryLight: "oklch(0.58 0.15 295.00)",
    primaryDark: "oklch(0.68 0.12 297.00)",
    fontSans: "Quicksand, sans-serif",
    description: "Timeless purple elegance",
    category: "colorful",
  },
  {
    name: "kodama-grove",
    title: "Kodama Grove",
    primaryLight: "oklch(0.62 0.12 140.00)",
    primaryDark: "oklch(0.72 0.14 142.00)",
    fontSans: "Source Serif 4, serif",
    description: "Forest spirits and natural harmony",
    category: "creative",
  },
  {
    name: "tangerine",
    title: "Tangerine",
    primaryLight: "oklch(0.72 0.18 50.00)",
    primaryDark: "oklch(0.78 0.16 52.00)",
    fontSans: "Poppins, sans-serif",
    description: "Vibrant citrus orange energy",
    category: "colorful",
  },
  {
    name: "quantum-rose",
    title: "Quantum Rose",
    primaryLight: "oklch(0.65 0.20 350.00)",
    primaryDark: "oklch(0.72 0.16 352.00)",
    fontSans: "Outfit, sans-serif",
    description: "Futuristic pink with quantum flair",
    category: "creative",
  },
  {
    name: "bold-tech",
    title: "Bold Tech",
    primaryLight: "oklch(0.58 0.22 245.00)",
    primaryDark: "oklch(0.68 0.20 247.00)",
    fontSans: "Roboto, sans-serif",
    description: "Strong technical blue presence",
    category: "branded",
  },
  {
    name: "elegant-luxury",
    title: "Elegant Luxury",
    primaryLight: "oklch(0.50 0.08 80.00)",
    primaryDark: "oklch(0.65 0.10 82.00)",
    fontSans: "Playfair Display, serif",
    description: "Gold accents with refined taste",
    category: "creative",
  },
  {
    name: "amber-minimal",
    title: "Amber Minimal",
    primaryLight: "oklch(0.70 0.14 75.00)",
    primaryDark: "oklch(0.76 0.12 77.00)",
    fontSans: "Inter, sans-serif",
    description: "Warm amber with clean lines",
    category: "minimal",
  },
  {
    name: "supabase",
    title: "Supabase",
    primaryLight: "oklch(0.65 0.18 155.00)",
    primaryDark: "oklch(0.72 0.16 157.00)",
    fontSans: "Inter, sans-serif",
    description: "Official Supabase green theme",
    category: "branded",
  },
  {
    name: "solar-dusk",
    title: "Solar Dusk",
    primaryLight: "oklch(0.68 0.16 40.00)",
    primaryDark: "oklch(0.74 0.14 42.00)",
    fontSans: "Montserrat, sans-serif",
    description: "Golden hour warmth and comfort",
    category: "colorful",
  },
  {
    name: "claymorphism",
    title: "Claymorphism",
    primaryLight: "oklch(0.75 0.10 280.00)",
    primaryDark: "oklch(0.80 0.08 282.00)",
    fontSans: "DM Sans, sans-serif",
    description: "Soft 3D clay-like surfaces",
    category: "creative",
  },
  {
    name: "clean-slate",
    title: "Clean Slate",
    primaryLight: "oklch(0.52 0.14 230.00)",
    primaryDark: "oklch(0.62 0.12 232.00)",
    fontSans: "Inter, sans-serif",
    description: "Fresh start with slate blues",
    category: "minimal",
  },
  {
    name: "caffeine",
    title: "Caffeine",
    primaryLight: "oklch(0.55 0.08 45.00)",
    primaryDark: "oklch(0.65 0.06 47.00)",
    fontSans: "Roboto, sans-serif",
    description: "Rich coffee browns for focus",
    category: "dark",
  },
  {
    name: "retro-arcade",
    title: "Retro Arcade",
    primaryLight: "oklch(0.65 0.28 320.00)",
    primaryDark: "oklch(0.72 0.25 322.00)",
    fontSans: "Space Mono, monospace",
    description: "80s arcade neon nostalgia",
    category: "creative",
  },
  {
    name: "candyland",
    title: "Candyland",
    primaryLight: "oklch(0.75 0.20 340.00)",
    primaryDark: "oklch(0.82 0.16 342.00)",
    fontSans: "Quicksand, sans-serif",
    description: "Sweet pastel candy colors",
    category: "colorful",
  },
  {
    name: "northern-lights",
    title: "Northern Lights",
    primaryLight: "oklch(0.62 0.18 175.00)",
    primaryDark: "oklch(0.70 0.15 177.00)",
    fontSans: "Inter, sans-serif",
    description: "Aurora borealis greens and blues",
    category: "colorful",
  },
  {
    name: "vintage-paper",
    title: "Vintage Paper",
    primaryLight: "oklch(0.58 0.06 60.00)",
    primaryDark: "oklch(0.68 0.04 62.00)",
    fontSans: "Libre Baskerville, serif",
    description: "Aged paper with sepia warmth",
    category: "creative",
  },
  {
    name: "starry-night",
    title: "Starry Night",
    primaryLight: "oklch(0.55 0.16 260.00)",
    primaryDark: "oklch(0.65 0.14 262.00)",
    fontSans: "Lora, serif",
    description: "Van Gogh inspired deep blues",
    category: "dark",
  },
];

// Sort themes alphabetically by title, but keep default first
export const sortedThemes = [
  themes[0],
  ...themes.slice(1).sort((a, b) => a.title.localeCompare(b.title)),
];

export const themeNames = themes.map((t) => t.name);

// Group themes by category
export const themesByCategory = {
  minimal: themes.filter((t) => t.category === "minimal"),
  colorful: themes.filter((t) => t.category === "colorful"),
  branded: themes.filter((t) => t.category === "branded"),
  creative: themes.filter((t) => t.category === "creative"),
  dark: themes.filter((t) => t.category === "dark"),
};

// Generate all theme values for next-themes (name-light and name-dark variants)
export const allThemeValues = themes.flatMap((t) => [
  `${t.name}-light`,
  `${t.name}-dark`,
]);

// Default theme
export const DEFAULT_THEME = "default-dark";
