import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { CodeBlockDoc } from "@/components/docs/code-block-doc";

export const metadata = {
  title: "Theme Structure",
  description: "Understanding the structure of tweakcn/theme-picker themes.",
};

export default function ThemeStructurePage() {
  return (
    <div className="space-y-12">
      {/* Hero */}
      <div className="space-y-4">
        <Badge variant="outline">Reference</Badge>
        <h1 className="text-4xl font-bold tracking-tight">Theme Structure</h1>
        <p className="text-xl text-muted-foreground max-w-2xl">
          A detailed look at what&apos;s included when you install a
          tweakcn/theme-picker theme and how the files are organized.
        </p>
      </div>

      {/* Files Created */}
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold">Files Created by CLI</h2>
        <p className="text-muted-foreground">
          When you run the install command, these files are created or modified:
        </p>

        <div className="space-y-4">
          <Card className="p-4">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-mono text-sm font-semibold">
                  styles/themes/[name].css
                </h3>
                <p className="text-sm text-muted-foreground mt-1">
                  The main theme CSS file with all variables for light and dark
                  modes.
                </p>
              </div>
              <Badge variant="secondary">Created</Badge>
            </div>
          </Card>

          <Card className="p-4">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-mono text-sm font-semibold">
                  components/theme-provider.tsx
                </h3>
                <p className="text-sm text-muted-foreground mt-1">
                  ThemeProvider component configured with next-themes.
                </p>
              </div>
              <Badge variant="secondary">Created/Updated</Badge>
            </div>
          </Card>

          <Card className="p-4">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-mono text-sm font-semibold">
                  app/globals.css or styles/globals.css
                </h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Updated to import the theme CSS and set up base styles.
                </p>
              </div>
              <Badge variant="outline">Modified</Badge>
            </div>
          </Card>

          <Card className="p-4">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-mono text-sm font-semibold">
                  package.json
                </h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Adds next-themes as a dependency if not present.
                </p>
              </div>
              <Badge variant="outline">Modified</Badge>
            </div>
          </Card>
        </div>
      </div>

      {/* Theme CSS Structure */}
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold">Theme CSS Structure</h2>
        <p className="text-muted-foreground">
          Each theme CSS file follows this structure:
        </p>

        <CodeBlockDoc
          filename="styles/themes/catppuccin.css"
          language="css"
          code={`/* ===========================================
   Catppuccin Theme for shadcn/ui
   Generated by tweakcn/theme-picker
   =========================================== */

/* Light Mode */
[data-theme="catppuccin-light"] {
  /* Base colors */
  --background: oklch(0.96 0.01 264.53);
  --foreground: oklch(0.44 0.04 279.33);

  /* Component colors */
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.44 0.04 279.33);
  --popover: oklch(0.86 0.01 268.48);
  --popover-foreground: oklch(0.44 0.04 279.33);

  /* Primary colors */
  --primary: oklch(0.55 0.25 297.02);
  --primary-foreground: oklch(1 0 0);

  /* Secondary colors */
  --secondary: oklch(0.86 0.01 268.48);
  --secondary-foreground: oklch(0.44 0.04 279.33);

  /* Muted colors */
  --muted: oklch(0.91 0.01 264.51);
  --muted-foreground: oklch(0.55 0.03 279.08);

  /* Accent colors */
  --accent: oklch(0.68 0.14 235.38);
  --accent-foreground: oklch(1 0 0);

  /* Destructive colors */
  --destructive: oklch(0.55 0.22 19.81);
  --destructive-foreground: oklch(1 0 0);

  /* Border and input */
  --border: oklch(0.81 0.02 271.2);
  --input: oklch(0.86 0.01 268.48);
  --ring: oklch(0.55 0.25 297.02);

  /* Chart colors */
  --chart-1: oklch(0.55 0.25 297.02);
  --chart-2: oklch(0.68 0.14 235.38);
  --chart-3: oklch(0.63 0.18 140.44);
  --chart-4: oklch(0.69 0.2 42.43);
  --chart-5: oklch(0.71 0.1 33.1);

  /* Sidebar */
  --sidebar: oklch(0.93 0.01 264.52);
  --sidebar-foreground: oklch(0.44 0.04 279.33);
  --sidebar-primary: oklch(0.55 0.25 297.02);
  --sidebar-primary-foreground: oklch(1 0 0);
  --sidebar-accent: oklch(0.68 0.14 235.38);
  --sidebar-accent-foreground: oklch(1 0 0);
  --sidebar-border: oklch(0.81 0.02 271.2);
  --sidebar-ring: oklch(0.55 0.25 297.02);

  /* Typography */
  --font-sans: Montserrat, sans-serif;
  --font-serif: Georgia, serif;
  --font-mono: Fira Code, monospace;

  /* Spacing and radius */
  --radius: 0.35rem;
  --spacing: 0.25rem;

  /* Shadows */
  --shadow-color: hsl(240 30% 25%);
  --shadow-opacity: 0.12;
  /* ... shadow scale ... */
}

/* Dark Mode */
[data-theme="catppuccin-dark"] {
  /* ... dark mode variables ... */
}`}
        />
      </div>

      {/* ThemeProvider Structure */}
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold">ThemeProvider Structure</h2>
        <p className="text-muted-foreground">
          The generated ThemeProvider component:
        </p>

        <CodeBlockDoc
          filename="components/theme-provider.tsx"
          language="tsx"
          code={`"use client"

import { ThemeProvider as NextThemesProvider } from "next-themes"
import { ReactNode } from "react"

// All available theme values
const themes = [
  "catppuccin-light",
  "catppuccin-dark",
  // ... other themes if installed
]

const DEFAULT_THEME = "catppuccin-dark"

export function ThemeProvider({ children }: { children: ReactNode }) {
  return (
    <NextThemesProvider
      attribute="data-theme"
      themes={themes}
      defaultTheme={DEFAULT_THEME}
      enableSystem={false}
      disableTransitionOnChange
    >
      {children}
    </NextThemesProvider>
  )
}`}
        />
      </div>

      {/* Variable Reference */}
      <div className="space-y-4">
        <h2 className="text-2xl font-semibold">Complete Variable Reference</h2>
        <p className="text-muted-foreground">
          All CSS variables defined in tweakcn/theme-picker themes:
        </p>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b">
                <th className="text-left py-3 px-4 font-medium">Variable</th>
                <th className="text-left py-3 px-4 font-medium">Usage</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--background</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Page/app background
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--foreground</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Primary text color
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--primary</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Primary brand color, buttons, links
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--secondary</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Secondary elements, less emphasis
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--muted</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Subdued backgrounds, disabled states
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--accent</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Highlights, hover states
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--destructive</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Error states, delete actions
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--card</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Card component backgrounds
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--popover</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Dropdown, popover backgrounds
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--border</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Border color for all elements
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--input</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Input field backgrounds
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--ring</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Focus ring color
                </td>
              </tr>
              <tr>
                <td className="py-3 px-4 font-mono text-xs">--radius</td>
                <td className="py-3 px-4 text-muted-foreground">
                  Base border radius
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
